### ISSUE TITLE
Cannot select shell nor editor

### ISSUE THREAD

**Issue by NatoBoram** [shiftkey/desktop#127]
## Description

In Options / Advanced, there's the options "External editor" and "Shell". I have both VSCode-Insiders and PowerShell installed, but I can't select them.

![shell-and-editor](https://user-images.githubusercontent.com/10495562/53825888-5a318980-3f45-11e9-8543-775e7593fa45.png)

## Version

* GitHub Desktop: `1.6.2-linux1`

* Operating system:
```yaml
OS: elementary OS 5.0 Juno x86_64 
Kernel: 4.15.0-46-generic 
Uptime: 1 hour, 4 mins 
Packages: 2214 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: Elementary [GTK3] 
Icons: Elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3535MiB / 7920MiB 
```

## Steps to Reproduce

1. Go to options / advanced

### Expected Behavior

I should be able to select my editor

### Actual Behavior

I can't select my editor

## Additional Information

I installed the latest Snap version.
