### ISSUE TITLE
unable to complete browser login flow 

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#134]
## Description

The latest `beta` snap can launch the browser login flow, but it doesn't seem to have the associated protocol handler registered to launch when the callback fires.

## Version
* GitHub Desktop: `1.6.5-linux6`
* Operating system: Ubuntu 18.04

## Steps to Reproduce
1. `snap install github-desktop --beta --classic`
2. launch the app
3. "Sign in using your browser"
4. Browser launches
5. Complete flow, browser indicates it is returning you to the app

### Expected Behavior
Welcome wizard proceeds to next step

### Actual Behavior
Nothing

## Additional Information
I gather something needs to be declared in the `snap.yaml` file like this, based on the [VSCode config](https://github.com/Microsoft/vscode/blob/master/resources/linux/snap/snapcraft.yaml#L58-L63): 

```
  url-handler:
    command: electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@ --open-url
    desktop: usr/share/applications/@@NAME@@-url-handler.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
```
